[project]
name = "backend"
version = "0.1.0"
description = "Backend API for docInfoExtraction."
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.11",
    "groq>=0.19.0",
    "instructor>=1.7.3",
    "mistralai>=1.5.1",
    "pymongo>=4.11.2",
    "sqlmodel>=0.0.24",
]
